# Generated by Django 2.2.2 on 2019-06-16 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('credits', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('licenseplate', models.CharField(max_length=8)),
                ('passengerqty', models.IntegerField(default=0)),
                ('drivers', models.ManyToManyField(to='ViajeroFrecuente.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateTimeField()),
                ('trip_from', models.CharField(max_length=255)),
                ('trip_to', models.CharField(max_length=255)),
                ('trip_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trip_passengerqty', models.IntegerField(default=0)),
                ('trip_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_driver', to='ViajeroFrecuente.AppUser')),
                ('trip_passengers', models.ManyToManyField(related_name='trip_passengers', to='ViajeroFrecuente.AppUser')),
                ('trip_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ViajeroFrecuente.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_date', models.DateTimeField()),
                ('qualification_value', models.IntegerField(default=0)),
                ('qualification_givenby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_givenby', to='ViajeroFrecuente.AppUser')),
                ('qualification_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ViajeroFrecuente.Trip')),
                ('qualification_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification_user', to='ViajeroFrecuente.AppUser')),
            ],
        ),
    ]
