# Generated by Django 2.2.2 on 2019-06-29 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ViajeroFrecuente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='qualification',
            name='qualification_comments',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_tripstatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trip_status', to='ViajeroFrecuente.TripStatus'),
            preserve_default=False,
        ),
    ]
