# Generated by Django 2.2.2 on 2019-06-29 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ViajeroFrecuente', '0002_auto_20190629_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_tripstatus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_status', to='ViajeroFrecuente.TripStatus'),
        ),
    ]
