# Generated by Django 2.2.2 on 2019-06-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViajeroFrecuente', '0003_auto_20190629_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='licenseplate',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='qualification',
            unique_together={('qualification_trip', 'qualification_user', 'qualification_givenby')},
        ),
    ]
